// FreeRTOS Configuration Constants
// This file includes constants automatically generated by build.rs
// that are synchronized with include/FreeRTOSConfig.h
//
// ⚠️ IMPORTANT: Do not modify this file manually!
// To change values, modify include/FreeRTOSConfig.h and recompile.

// Include the file automatically generated by the build script
include!(concat!(env!("OUT_DIR"), "/freertos_constants_generated.rs"));

